"""Run the HypoDD `hypoDD` binary with ph2dt outputs (and optionally the dt.cc
generated by 18_growclust_xc_prep). Parses hypoDD.reloc into a CSV.

Reads (in hypodd/<label>/): event.sel, dt.ct, station.dat, [dt.cc]
Writes:
    hypoDD.inp        - control file
    hypoDD.loc        - initial absolute locations
    hypoDD.reloc      - relocated catalog
    hypoDD.sta        - station residuals
    hypoDD.res        - data residuals
    hypoDD.log        - full log
    catalogs/hypodd_<label>.csv  - parsed reloc file
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
DEFAULT_BIN = Path("/home/jovyan/HypoDD/src/hypoDD/hypoDD")


def write_velocity(csv_path: Path, run_dir: Path, datum_shift_km: float = 0.0,
                   max_layers: int = 30):
    """Return (n_layers, tops, vp, vs) for hypoDD from configs/velocity_model.csv.

    - Rock only. The CSV carries a 1.3 km water column (vs=0.5 km/s). hypoDD flattens
      every OBS to elevation 0, so the model must be on a SEAFLOOR datum: drop the
      water rows and re-zero depth at `datum_shift_km` (the representative water depth
      under the EVENTS, not the array), extending the first rock velocity up to 0.
      Previously the water rows were kept, the vs<=0.05 guard never fired (vs=0.5), and
      S waves were propagated through 'water' at Vp/Vs = 2.91.
    - Layers merged by velocity CONTRAST, never by stride. The old code took every
      other distinct-velocity row, which assigns each interval the velocity of its
      shallower half (systematically slow, +138 ms over 0-31 km) and dropped the
      1.3 km sediment layer outright.
    - Missing model is an error, not a silent 5-layer continental default.
    """
    if not csv_path.exists():
        raise SystemExit(f"velocity model not found: {csv_path} -- refusing to substitute a default")
    vm = pd.read_csv(csv_path)
    vp_col = "vp_kms" if "vp_kms" in vm.columns else "vp_km_s"
    vs_col = "vs_kms" if "vs_kms" in vm.columns else "vs_km_s"
    vm = vm.sort_values("depth_km").reset_index(drop=True)
    rock = vm[vm[vp_col] > 1.6].copy()                 # drop the water column
    if datum_shift_km:
        rock["depth_km"] = rock["depth_km"] - datum_shift_km
        rock = rock[rock["depth_km"] >= 0.0]
        top = rock.iloc[[0]].copy(); top["depth_km"] = 0.0   # extend first rock Vp to the datum
        rock = pd.concat([top, rock], ignore_index=True)
    else:
        if rock["depth_km"].iloc[0] > 0:
            top = rock.iloc[[0]].copy(); top["depth_km"] = 0.0
            rock = pd.concat([top, rock], ignore_index=True)
    # merge adjacent rows whose Vp differs by < 1%
    tops, vp, vs = [float(rock.depth_km.iloc[0])], [float(rock[vp_col].iloc[0])], [float(rock[vs_col].iloc[0])]
    for _, r in rock.iloc[1:].iterrows():
        if abs(r[vp_col] - vp[-1]) / vp[-1] >= 0.01:
            tops.append(float(r.depth_km)); vp.append(float(r[vp_col])); vs.append(float(r[vs_col]))
    # if still too many, merge the smallest contrasts first (never by stride)
    while len(tops) > max_layers:
        j = min(range(1, len(vp)), key=lambda i: abs(vp[i] - vp[i-1]))
        del tops[j]; del vp[j]; del vs[j]
    assert all(b > a for a, b in zip(tops, tops[1:])), "layer tops not increasing"
    assert all(v > 1.6 for v in vp), "water velocity leaked into the rock model"
    return len(tops), tops, vp, vs


def make_control(label: str, n_lay: int, tops, vps, vss,
                 with_xc: bool, niter_ct: int, niter_cc: int,
                 damp: float = 200.0, iaq: int = 1,
                 wrct: float = 6.0, wrct_last: float = 4.0, wdct_last: float = -999.0) -> str:
    """Build a hypoDD.inp using IMOD=1 (variable Vp/Vs per layer) so the water
    layer's near-zero Vs is handled correctly rather than being forced to
    Vp/1.78 (which would put S waves in water, a non-physical state)."""
    dt_cc = "dt.cc"
    # Reweighting schedule. Tags moved off the data line so the Fortran
    # free-format read sees exactly 10 numbers per row.
    # DAMP, WRCT and WDCT used to be hard-coded (20 / 10,8 / -999,4). On the v4
    # baseline DAMP=20 gave condition numbers of 1,151-6,181 against a user-guide
    # target of ~40-80: two orders of magnitude under-damped, so LSQR fitted noise
    # along the least-resolved direction (relative depth) and compressed the depth
    # axis by 80% (dz slope -0.80 vs the starting locations). WRCT 10/8 is
    # effectively no outlier rejection on picks associated with a 0.5 s tolerance
    # (conventional 6 -> 4). WDCT=4 < MAXSEP=5 culled 21% of pairs mid-run,
    # preferentially the sparse ends of the depth distribution. IAQ=0 kept
    # 600-1,450 airquakes per iteration, clamped to the datum each pass.
    blocks = []
    D = f"{damp:.0f}"
    if with_xc:
        for _ in range(niter_ct):
            blocks.append(f"  3     -9   -9    -999   -999   1.0    0.5    {wrct:.0f}    -999  {D}")
        for _ in range(niter_cc):
            blocks.append(f"  3     1.0   0.5    5      2    1.0    0.5    {wrct:.0f}      2   {D}")
    else:
        for _ in range(niter_ct):
            blocks.append(f"  5     -9   -9    -999   -999   1.0    0.5    {wrct:.0f}    -999  {D}")
        blocks.append(f"  5     -9   -9    -999   -999   1.0    0.5    {wrct_last:.0f}    {wdct_last:.0f}  {D}")
    nset = len(blocks)
    reweight_block = "\n".join(blocks)
    idat = 3 if with_xc else 2

    tops_line = " ".join(f"{t:.3f}" for t in tops)
    vp_line   = " ".join(f"{v:.3f}" for v in vps)
    # IMOD=1 wants per-layer Vp/Vs. Water Vs ~= 0 would divide-by-zero; clamp
    # to a very large ratio (200) to encode "no S waves here".
    ratios = []
    for vp, vs in zip(vps, vss):
        if vs is None or pd.isna(vs) or vs <= 0.05:
            ratios.append(200.0)
        else:
            ratios.append(vp / vs)
    ratios_line = " ".join(f"{r:.3f}" for r in ratios)

    ctl = f"""hypoDD_2
* hypoDD control file -- label {label}
*--- input file selection:
{dt_cc}
dt.ct
event.sel
station.dat
*
*--- output file selection:
hypoDD.loc
hypoDD.reloc
hypoDD.sta
hypoDD.res
hypoDD.src
*
*--- data type selection:
* IDAT  IPHA  MAXDIST   (MAXDIST=100 km matches ph2dt and array aperture)
  {idat}     3    100
*
*--- event clustering:
* OBSCC OBSCT MINDIST MAXDIST MAXGAP
   {0 if not with_xc else 8}     8    -999    -999    -999
*
*--- solution control:
* ISTART  ISOLV  IAQ  NSET    (ISTART=1: catalog hypocenters as trial sources;
*                              ISOLV=2: LSQR;
*                              IAQ=0: keep shallow events instead of stopping)
    1      2     {iaq}    {nset}
*
*--- data weighting and re-weighting:
* NITER  WTCCP  WTCCS  WRCC  WDCC  WTCTP  WTCTS  WRCT  WDCT DAMP
{reweight_block}
*
*--- forward model (IMOD=1 -> 1D layered, variable Vp/Vs per layer):
* IMOD
1
* TOP (km), terminate with -9
{tops_line} -9
* VEL Vp (km/s), terminate with -9
{vp_line} -9
* RATIO Vp/Vs per layer, terminate with -9    (water = 200 encodes 'no S')
{ratios_line} -9
*
*--- cluster / event selection (0 = all clusters):
* CID
  0
* ID
"""
    return ctl


def parse_reloc(path: Path) -> pd.DataFrame:
    """hypoDD.reloc columns (24):
    ID LAT LON DEP X Y Z EX EY EZ YR MO DY HR MI SC MAG NCCP NCCS NCTP NCTS RCC RCT CID
    """
    cols = ["id","lat","lon","dep","x","y","z","ex","ey","ez",
            "yr","mo","dy","hr","mi","sc","mag",
            "nccp","nccs","nctp","ncts","rcc","rct","cid"]
    df = pd.read_csv(path, names=cols, sep=r"\s+", engine="python")
    return df


def apply_depth_sanity_filter(df: pd.DataFrame, datum_shift_km: float) -> pd.DataFrame:
    """On a seafloor datum, 'physical' means depth >= 0 (below the representative
    seafloor). Also write depth_bsl_km so downstream never has to guess the frame."""
    df["depth_datum"] = "seafloor" if datum_shift_km else "as_input"
    df["datum_shift_km"] = datum_shift_km
    df["depth_bsl_km"] = df["dep"] + datum_shift_km
    df["physical"] = df["dep"] >= 0.0
    n_bad = int((~df["physical"]).sum())
    print(f"  depth-sanity: {n_bad:,} events relocated above the datum "
          f"(hypoDD 'airquakes'; physical=False). Datum = {datum_shift_km} km BSL.")
    return df


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--label", default="picker_only")
    ap.add_argument("--binary", default=str(DEFAULT_BIN))
    ap.add_argument("--velocity-csv", default="configs/velocity_model.csv")
    ap.add_argument("--with-xc", action="store_true",
                    help="Include cross-correlation dt.cc in the inversion.")
    ap.add_argument("--niter-ct", type=int, default=2)
    ap.add_argument("--niter-cc", type=int, default=2)
    ap.add_argument("--out-suffix", default="")
    ap.add_argument("--datum-shift-km", type=float, default=None,
                    help="seafloor datum used by script 22 (read from hypodd_datum.json if omitted)")
    ap.add_argument("--max-layers", type=int, default=30, help="hypoDD MAXLAY is 50")
    ap.add_argument("--damp", type=float, default=200.0,
                    help="LSQR damping. Tune until the log's CND is ~40-80. Was 20 (CND in the thousands).")
    ap.add_argument("--iaq", type=int, default=1, choices=[0, 1],
                    help="1 = remove airquakes (use for tuning); 0 = keep. Was 0.")
    ap.add_argument("--wrct", type=float, default=6.0, help="catalogue residual cutoff, x std (sets 1..n-1). Was 10.")
    ap.add_argument("--wrct-last", type=float, default=4.0, help="residual cutoff in the last set. Was 8.")
    ap.add_argument("--wdct-last", type=float, default=-999.0,
                    help="pair-distance cull (km) in the last set; -999 = none. Was 4 (< MAXSEP 5).")
    args = ap.parse_args()

    run_dir = REPO / "hypodd" / args.label
    for needed in ("phase.dat", "station.dat", "event.sel", "dt.ct"):
        if not (run_dir / needed).exists():
            sys.exit(f"Missing {run_dir/needed}; run 22 + 23 first.")

    if args.with_xc and not (run_dir / "dt.cc").exists():
        src = REPO / "growclust" / args.label / "dt.cc"
        if src.exists():
            shutil.copy(src, run_dir / "dt.cc")
            print(f"  copied {src} -> {run_dir/'dt.cc'}")
        else:
            sys.exit(f"Need dt.cc with --with-xc; not found at {src}.")

    import json
    shift = args.datum_shift_km
    if shift is None:
        dj = run_dir / "hypodd_datum.json"
        shift = float(json.loads(dj.read_text())["datum_shift_km"]) if dj.exists() else 0.0
    print(f"  depth datum: seafloor, shift {shift} km BSL" if shift else "  depth datum: as input")
    n_lay, tops, vps, vss = write_velocity(REPO / args.velocity_csv, run_dir, shift, args.max_layers)
    print(f"  velocity model: {n_lay} layers (rock only), tops {tops[0]:.2f}-{tops[-1]:.2f} km, "
          f"Vp {min(vps):.2f}-{max(vps):.2f}")
    ctl = make_control(args.label, n_lay, tops, vps, vss,
                       args.with_xc, args.niter_ct, args.niter_cc,
                       damp=args.damp, iaq=args.iaq, wrct=args.wrct,
                       wrct_last=args.wrct_last, wdct_last=args.wdct_last)
    print(f"  inversion: DAMP={args.damp:.0f}  IAQ={args.iaq}  WRCT={args.wrct:.0f}/{args.wrct_last:.0f}  "
          f"WDCT(last set)={args.wdct_last:.0f}")
    (run_dir / "hypoDD.inp").write_text(ctl)
    print(f"Wrote {run_dir/'hypoDD.inp'}")

    print(f"\nRunning {args.binary} in {run_dir} ...")
    # No subprocess timeout -- year-long LSQR on a single big cluster can take
    # tens of hours and we'd rather have a real result than a SIGKILL'd one.
    # If you need to abort, do it manually by killing the hypoDD PID.
    proc = subprocess.run(
        [args.binary, "hypoDD.inp"],
        cwd=run_dir,
        capture_output=True,
    )
    # Save BOTH stdout and stderr so silent crashes are visible.
    log = proc.stdout.decode(errors="replace")
    if proc.stderr:
        log += "\n---- stderr ----\n" + proc.stderr.decode(errors="replace")
    (run_dir / "hypoDD.log").write_text(log)
    print(log[-2000:])
    if proc.returncode != 0:
        print(f"[hypoDD returned {proc.returncode}]")
    reloc = run_dir / "hypoDD.reloc"
    if not reloc.exists() or reloc.stat().st_size == 0:
        sys.exit(f"hypoDD did not produce {reloc}")
    df = parse_reloc(reloc)
    n_in = sum(1 for _ in (run_dir / "event.sel").open())
    print(f"  events: {n_in:,} in event.sel -> {len(df):,} relocated "
          f"({n_in-len(df):,} lost in hypoDD, {(n_in-len(df))/max(n_in,1)*100:.1f}%)")
    df = apply_depth_sanity_filter(df, shift)
    out_csv = REPO / "catalogs" / f"hypodd_{args.label}{args.out_suffix}.csv"
    df.to_csv(out_csv, index=False)
    print(f"\nWrote {out_csv}  ({len(df):,} relocated events)")


if __name__ == "__main__":
    sys.exit(main() or 0)
