"""Run the HypoDD `hypoDD` binary with ph2dt outputs (and optionally the dt.cc
generated by 18_growclust_xc_prep). Parses hypoDD.reloc into a CSV.

Reads (in hypodd/<label>/): event.sel, dt.ct, station.dat, [dt.cc]
Writes:
    hypoDD.inp        - control file
    hypoDD.loc        - initial absolute locations
    hypoDD.reloc      - relocated catalog
    hypoDD.sta        - station residuals
    hypoDD.res        - data residuals
    hypoDD.log        - full log
    catalogs/hypodd_<label>.csv  - parsed reloc file
"""
from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parent.parent
DEFAULT_BIN = Path("/home/jovyan/HypoDD/src/hypoDD/hypoDD")


def write_velocity(csv_path: Path, run_dir: Path):
    """Read configs/velocity_model.csv and return (n_layers, tops, vp, vs).

    hypoDD IMOD=1 uses per-layer Vp/Vs (rather than a single fixed ratio), which
    matters because the water layer has no S waves (Vs ~= 0, Vp/Vs >> 1.78). We
    return the Vs list so the caller can write the per-layer ratio block.

    csv columns: depth_km, vp_kms, vs_kms."""
    if not csv_path.exists():
        tops = [0.0, 2.0, 5.0, 15.0, 30.0]
        vp   = [3.0, 5.0, 6.0, 6.5, 7.5]
        vs   = [v / 1.78 for v in vp]
        return len(tops), tops, vp, vs
    vm = pd.read_csv(csv_path)
    vp_col = "vp_kms" if "vp_kms" in vm.columns else "vp_km_s"
    vs_col = "vs_kms" if "vs_kms" in vm.columns else "vs_km_s"
    vm = vm.sort_values("depth_km").reset_index(drop=True)
    # Collapse constant-vp sections to keep the model coarse.
    keep = [0]
    for i in range(1, len(vm)):
        if vm[vp_col].iloc[i] != vm[vp_col].iloc[i-1]:
            keep.append(i)
    vm_layers = vm.iloc[keep].reset_index(drop=True)
    # Cap to <= 15 layers but ALWAYS include the deepest entry so the model
    # extends through the seismic-event depth range.
    if len(vm_layers) > 15:
        stride = max(1, len(vm_layers) // 15)
        sub_idx = list(range(0, len(vm_layers), stride))
        if sub_idx[-1] != len(vm_layers) - 1:
            sub_idx.append(len(vm_layers) - 1)
        vm_layers = vm_layers.iloc[sub_idx].reset_index(drop=True)
    tops = vm_layers["depth_km"].tolist()
    vp = vm_layers[vp_col].tolist()
    vs = vm_layers[vs_col].tolist()
    return len(tops), tops, vp, vs


def make_control(label: str, n_lay: int, tops, vps, vss,
                 with_xc: bool, niter_ct: int, niter_cc: int) -> str:
    """Build a hypoDD.inp using IMOD=1 (variable Vp/Vs per layer) so the water
    layer's near-zero Vs is handled correctly rather than being forced to
    Vp/1.78 (which would put S waves in water, a non-physical state)."""
    dt_cc = "dt.cc"
    # Reweighting schedule. Tags moved off the data line so the Fortran
    # free-format read sees exactly 10 numbers per row.
    blocks = []
    if with_xc:
        for _ in range(niter_ct):
            blocks.append("  3     -9   -9    -999   -999   1.0    0.5    10    -999  20")
        for _ in range(niter_cc):
            blocks.append("  3     1.0   0.5    5      2    1.0    0.5    9      2   20")
    else:
        for _ in range(niter_ct):
            blocks.append("  5     -9   -9    -999   -999   1.0    0.5    10    -999  20")
        blocks.append("  5     -9   -9    -999   -999   1.0    0.5    8      4    20")
    nset = len(blocks)
    reweight_block = "\n".join(blocks)
    idat = 3 if with_xc else 2

    tops_line = " ".join(f"{t:.3f}" for t in tops)
    vp_line   = " ".join(f"{v:.3f}" for v in vps)
    # IMOD=1 wants per-layer Vp/Vs. Water Vs ~= 0 would divide-by-zero; clamp
    # to a very large ratio (200) to encode "no S waves here".
    ratios = []
    for vp, vs in zip(vps, vss):
        if vs is None or pd.isna(vs) or vs <= 0.05:
            ratios.append(200.0)
        else:
            ratios.append(vp / vs)
    ratios_line = " ".join(f"{r:.3f}" for r in ratios)

    ctl = f"""hypoDD_2
* hypoDD control file -- label {label}
*--- input file selection:
{dt_cc}
dt.ct
event.sel
station.dat
*
*--- output file selection:
hypoDD.loc
hypoDD.reloc
hypoDD.sta
hypoDD.res
hypoDD.src
*
*--- data type selection:
* IDAT  IPHA  MAXDIST   (MAXDIST=100 km matches ph2dt and array aperture)
  {idat}     3    100
*
*--- event clustering:
* OBSCC OBSCT MINDIST MAXDIST MAXGAP
   {0 if not with_xc else 8}     8    -999    -999    -999
*
*--- solution control:
* ISTART  ISOLV  IAQ  NSET    (ISTART=1: catalog hypocenters as trial sources;
*                              ISOLV=2: LSQR;
*                              IAQ=0: keep shallow events instead of stopping)
    1      2     0    {nset}
*
*--- data weighting and re-weighting:
* NITER  WTCCP  WTCCS  WRCC  WDCC  WTCTP  WTCTS  WRCT  WDCT DAMP
{reweight_block}
*
*--- forward model (IMOD=1 -> 1D layered, variable Vp/Vs per layer):
* IMOD
1
* TOP (km), terminate with -9
{tops_line} -9
* VEL Vp (km/s), terminate with -9
{vp_line} -9
* RATIO Vp/Vs per layer, terminate with -9    (water = 200 encodes 'no S')
{ratios_line} -9
*
*--- cluster / event selection (0 = all clusters):
* CID
  0
* ID
"""
    return ctl


def parse_reloc(path: Path) -> pd.DataFrame:
    """hypoDD.reloc columns (24):
    ID LAT LON DEP X Y Z EX EY EZ YR MO DY HR MI SC MAG NCCP NCCS NCTP NCTS RCC RCT CID
    """
    cols = ["id","lat","lon","dep","x","y","z","ex","ey","ez",
            "yr","mo","dy","hr","mi","sc","mag",
            "nccp","nccs","nctp","ncts","rcc","rct","cid"]
    df = pd.read_csv(path, names=cols, sep=r"\s+", engine="python")
    return df


def apply_depth_sanity_filter(df: pd.DataFrame, station_csv: Path) -> pd.DataFrame:
    """Flag events whose depth is shallower than the local bathymetric depth.
    Physically no event can be in the water column. We don't delete -- just
    add a `physical` boolean column so downstream can decide what to do."""
    try:
        st = pd.read_csv(station_csv)
        # Use median water_depth_m of OBS as a coarse seafloor depth check.
        if "water_depth_m" in st.columns:
            zx = st[st["network"] == "ZX"]
            if len(zx) > 0:
                median_seafloor_km = zx["water_depth_m"].median() / 1000.0
                df["physical"] = df["dep"] >= median_seafloor_km
                n_bad = (~df["physical"]).sum()
                print(f"  depth-sanity: {n_bad:,} events shallower than median "
                      f"seafloor ({median_seafloor_km:.2f} km) flagged physical=False")
                return df
    except Exception as e:
        print(f"  depth-sanity filter skipped: {e}")
    df["physical"] = True
    return df


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--label", default="picker_only")
    ap.add_argument("--binary", default=str(DEFAULT_BIN))
    ap.add_argument("--velocity-csv", default="configs/velocity_model.csv")
    ap.add_argument("--with-xc", action="store_true",
                    help="Include cross-correlation dt.cc in the inversion.")
    ap.add_argument("--niter-ct", type=int, default=2)
    ap.add_argument("--niter-cc", type=int, default=2)
    ap.add_argument("--out-suffix", default="")
    args = ap.parse_args()

    run_dir = REPO / "hypodd" / args.label
    for needed in ("phase.dat", "station.dat", "event.sel", "dt.ct"):
        if not (run_dir / needed).exists():
            sys.exit(f"Missing {run_dir/needed}; run 22 + 23 first.")

    if args.with_xc and not (run_dir / "dt.cc").exists():
        src = REPO / "growclust" / args.label / "dt.cc"
        if src.exists():
            shutil.copy(src, run_dir / "dt.cc")
            print(f"  copied {src} -> {run_dir/'dt.cc'}")
        else:
            sys.exit(f"Need dt.cc with --with-xc; not found at {src}.")

    n_lay, tops, vps, vss = write_velocity(REPO / args.velocity_csv, run_dir)
    print(f"  velocity model: {n_lay} layers, tops {tops[0]:.2f}-{tops[-1]:.2f} km")
    ctl = make_control(args.label, n_lay, tops, vps, vss,
                       args.with_xc, args.niter_ct, args.niter_cc)
    (run_dir / "hypoDD.inp").write_text(ctl)
    print(f"Wrote {run_dir/'hypoDD.inp'}")

    print(f"\nRunning {args.binary} in {run_dir} ...")
    # No subprocess timeout -- year-long LSQR on a single big cluster can take
    # tens of hours and we'd rather have a real result than a SIGKILL'd one.
    # If you need to abort, do it manually by killing the hypoDD PID.
    proc = subprocess.run(
        [args.binary, "hypoDD.inp"],
        cwd=run_dir,
        capture_output=True,
    )
    # Save BOTH stdout and stderr so silent crashes are visible.
    log = proc.stdout.decode(errors="replace")
    if proc.stderr:
        log += "\n---- stderr ----\n" + proc.stderr.decode(errors="replace")
    (run_dir / "hypoDD.log").write_text(log)
    print(log[-2000:])
    if proc.returncode != 0:
        print(f"[hypoDD returned {proc.returncode}]")
    reloc = run_dir / "hypoDD.reloc"
    if not reloc.exists() or reloc.stat().st_size == 0:
        sys.exit(f"hypoDD did not produce {reloc}")
    df = parse_reloc(reloc)
    df = apply_depth_sanity_filter(df, REPO / "catalogs" / "station_geometry.csv")
    out_csv = REPO / "catalogs" / f"hypodd_{args.label}{args.out_suffix}.csv"
    df.to_csv(out_csv, index=False)
    print(f"\nWrote {out_csv}  ({len(df):,} relocated events)")


if __name__ == "__main__":
    sys.exit(main() or 0)
