"""Generate the NLLoc control file for a labelled run.

The TT-grid prefix is selectable:
  - "ORCA"     -> the 15 BRA OBS grids shipped via Stingray (60x40x25 km, 0.2 km)
  - "ORCA_v2"  -> the extended grid built by scripts 38/39
                  (230x180x25 km, 0.4 km, all 38 stations)

Stations are auto-populated from station_geometry.csv, filtered to those
that actually have a .time.hdr under the chosen prefix.

Writes:
    nlloc/run/<label>.in
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parent.parent

# Grid headers we know about. Origin/spacing must match the actual .time.hdr
# files; both are derived from the same Stingray TRANS SIMPLE projection.
GRID_LAYOUTS = {
    "ORCA":    dict(nx=301, ny=201, nz=126, x0=-29.8, y0=-20.0,  dx=0.2),
    "ORCA_v2": dict(nx=576, ny=451, nz=64,  x0=-150.0, y0=-110.0, dx=0.4),
    "ORCA_v3": dict(nx=576, ny=451, nz=64,  x0=-150.0, y0=-110.0, dx=0.4),
    "ORCA_v4": dict(nx=576, ny=451, nz=64,  x0=-150.0, y0=-110.0, dx=0.4),
    # v5 = the v4 model with pykonal (FMM) travel-time grids instead of Grid2Time (script 59)
    "ORCA_v5": dict(nx=576, ny=451, nz=64,  x0=-150.0, y0=-110.0, dx=0.4),
}


def stations_with_grids(tt_dir: Path, prefix: str) -> set[str]:
    return {h.name.split(".")[2] for h in tt_dir.glob(f"{prefix}.P.*.time.hdr")}


def build_gtsrce(station_geom_csv: Path, available: set[str]) -> str:
    st = pd.read_csv(station_geom_csv)
    lines = []
    for _, r in st.iterrows():
        if r.station not in available:
            continue
        # TRUE depth, positive down, sea-level datum. See the note in script 39:
        # fields are lat lon DEPTH ELEV, and every station was previously pinned
        # to 0.0 regardless of its 785-1943 m water depth.
        if bool(getattr(r, "on_seafloor", False)) and float(r.water_depth_m or 0) > 0:
            depth_km = float(r.water_depth_m) / 1000.0
        else:
            # Clamp at 0 -- see the note in script 39.
            depth_km = max(0.0, -float(r.elevation_m or 0.0) / 1000.0)
        lines.append(f"GTSRCE {r.station} LATLON  "
                     f"{r.latitude:.6f} {r.longitude:.6f} {depth_km:.4f} 0.0")
    return "\n".join(lines)


CONTROL_TEMPLATE = """# NLLoc control file -- {label}
# generated by scripts/29_write_nlloc_control.py

CONTROL 1 54321
TRANS SIMPLE -62.4413 -58.44 36

GTMODE GRID3D ANGLES_NO
GTFILES ./nlloc/model/{prefix} ./nlloc/time/{prefix} P
{gtsrce}

# ----- NLLoc -----

LOCSIG bransfield-eq pipeline
LOCCOM {label}
LOCFILES {obs_path} NLLOC_OBS {tt_root} {out_root}
LOCHYPOUT SAVE_NLLOC_ALL SAVE_NLLOC_SUM
LOCSEARCH OCT 9 7 5 0.001 100000 5000 0 0
LOCGRID {nx} {ny} {nz_loc}  {x0} {y0} 0.0  {dx} {dx} {dx}  PROB_DENSITY SAVE
LOCMETH GAU_ANALYTIC 100 4 -1 -1 {vpvs} -1 -1 1
LOCGAU 0.1 0.0
LOCGAU2 0.01 0.05 2.0
LOCPHASEID P P p
LOCPHASEID S S s
LOCQUAL2ERR 0.1 0.5 1.0 2.0 99999.9
{delays}
"""


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--label", default="picker_only_no_shots")
    p.add_argument("--vpvs", type=float, default=1.78)
    p.add_argument("--delays", default=None,
                   help="file of LOCDELAY lines (station P/S time delays, s, positive = station late; NLLoc subtracts them from the observed times). Default: none")
    p.add_argument("--tt-prefix", default="ORCA_v3",
                   choices=sorted(GRID_LAYOUTS.keys()))
    args = p.parse_args()

    layout = dict(GRID_LAYOUTS[args.tt_prefix])
    # One cell shallower than the TT grid: see the LOCGRID note in the template.
    layout["nz_loc"] = layout["nz"] - 1
    tt_dir = REPO / "nlloc" / "time"
    available = stations_with_grids(tt_dir, args.tt_prefix)
    if not available:
        raise SystemExit(f"no .time.hdr files for prefix {args.tt_prefix!r}")
    gtsrce = build_gtsrce(REPO / "catalogs" / "station_geometry.csv", available)
    if not gtsrce:
        raise SystemExit("no GTSRCE rows; station_geometry.csv mismatch with time grids")

    obs_path = f"nlloc/obs/{args.label}.obs"
    out_dir = REPO / "nlloc" / "output" / args.label
    out_dir.mkdir(parents=True, exist_ok=True)
    out_root = f"nlloc/output/{args.label}/loc"
    tt_root = f"nlloc/time/{args.tt_prefix}"

    text = CONTROL_TEMPLATE.format(
        label=args.label,
        prefix=args.tt_prefix,
        gtsrce=gtsrce,
        obs_path=obs_path,
        tt_root=tt_root,
        out_root=out_root,
        vpvs=args.vpvs,
        delays=(Path(args.delays).read_text().rstrip() if args.delays else "# no LOCDELAY"),
        **layout,
    )
    run_dir = REPO / "nlloc" / "run"
    run_dir.mkdir(parents=True, exist_ok=True)
    ctrl_path = run_dir / f"{args.label}.in"
    ctrl_path.write_text(text)
    print(f"wrote {ctrl_path}  ({len(gtsrce.splitlines())} stations, "
          f"tt_prefix={args.tt_prefix})")


if __name__ == "__main__":
    main()
