#!/usr/bin/env bash
# hypoDD 3D on the v5 standard tier WITH cross-correlation differential times.
#
# Stage 1 builds a fresh run directory `hypodd/year_v5_3d_xc/` from the existing
# `hypodd/year_v5_3d/` inputs (nothing in year_v5_3d is modified: it is the
# catalogue-only baseline and its numbers are quoted from its own run24.log).
# Stage 2 makes dt.cc with scripts/63_xcorr_dtcc.py.
# Stage 3 runs hypoDD with IDAT=3 (ct + cc) using the SAME 3D forward model and
# inversion controls as the baseline, so the only difference is the cc data.
#
#   bash scripts/64_run_hypodd_xc.sh [--skip-xc] [--workers N]
#
set -euo pipefail
cd "$(dirname "$0")/.."
export PYTHONPATH=src

SRC=hypodd/year_v5_3d
DST=hypodd/year_v5_3d_xc
MOD3D=nlloc/model/ORCA_v4.hypodd3d_fine.vel
WORKERS=8
SKIP_XC=0
while [ $# -gt 0 ]; do
  case "$1" in
    --skip-xc) SKIP_XC=1; shift ;;
    --workers) WORKERS="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

# ---- stage 1: fresh copy of the baseline inputs (never the outputs)
mkdir -p "$DST"
for f in dt.ct event.dat event.sel phase.dat station.dat station.sel \
         ph2dt.inp ph2dt_summary.json hypodd_datum.json; do
  [ -f "$SRC/$f" ] && cp -f "$SRC/$f" "$DST/$f"
done
echo "inputs copied $SRC -> $DST"
ls -l "$DST"

# ---- stage 2: cross-correlation dt.cc
if [ "$SKIP_XC" -eq 0 ]; then
  python3 scripts/63_xcorr_dtcc.py --self-test
  /usr/bin/time -v python3 scripts/63_xcorr_dtcc.py \
      --label year_v5_3d --out "$DST/dt.cc" --workers "$WORKERS" \
      2>&1 | tee "$DST/xcorr.log"
fi
test -s "$DST/dt.cc"
echo "dt.cc rows: $(grep -vc '^#' "$DST/dt.cc")   pairs: $(grep -c '^#' "$DST/dt.cc")"

# ---- stage 3: hypoDD 3D, ct + cc.  Same flags as the baseline plus --with-xc.
# Baseline (hypodd/year_v5_3d/run24.log) was:
#   --imod 9 --mod3d $MOD3D --istart 2 --damp 400 --iaq 1   (no --with-xc)
#
# OBSCC: scripts/24_run_hypodd.py writes "OBSCC OBSCT = 8 8" whenever --with-xc
# is given.  cluster1.f links an event pair when its TOTAL observation count
# reaches minobs_cc + minobs_ct, i.e. 16 with those values -- and only 1.46% of
# the 326,280 dt.ct pairs have 16 observations (ph2dt ran with MINOBS 8; the mean
# is 9.16).  Leaving it at 8/8 would therefore rebuild the clusters from 1.5% of
# the pairs and the ct+cc run would not be comparable with the ct baseline at
# all.  The user guide's own IDAT=3 example (p.19) uses "OBSCC OBSCT = 0 8".  So
# the control file is generated by script 24 (--write-only, nothing in script 24
# is modified) and the OBSCC field alone is patched to 0 here, in this run's own
# hypoDD.inp.  Everything else is byte-identical to what script 24 emits.
python3 scripts/24_run_hypodd.py --label year_v5_3d_xc --with-xc \
    --imod 9 --mod3d "$MOD3D" --istart 2 --damp 400 --iaq 1 \
    --niter-ct 2 --niter-cc 1 --write-only 2>&1 | tee "$DST/run24.log"

python3 - "$DST/hypoDD.inp" <<'PY' 2>&1 | tee -a "$DST/run24.log"
import re, sys
p = sys.argv[1]
t = open(p).read()

# (1) OBSCC 8 -> 0.  See the comment above.
t, n = re.subn(r"(?m)^(\s*)8(\s+8\s+-999\s+-999\s+-999\s*)$", r"\g<1>0\g<2>", t)
assert n == 1, f"expected exactly one OBSCC line, patched {n}"

# (2) Re-weighting schedule.  Script 24's --with-xc schedule opens with
# niter_ct sets carrying WTCCP = WTCCS = -9 ("cc not yet used").  weighting.f
# computes dt_wt = wt_ccp * dt_qual, so -9 makes EVERY cross-correlation weight
# negative; hypoDD.f then calls skip(), and skip.f COMPACTS the data arrays,
# physically deleting every observation with dt_wt < minwght.  The cc data are
# gone for good and the later cc sets have nothing to weight.  Measured: the
# first ct+cc attempt read "# cross corr P dtimes = 80851 / S = 65590" and then
# reported CC = 0% and RMSCC = NaN on all 25 printed iterations.
# Fix (this is also how the user guide's own IDAT=3 example, p.19, is built):
# give cc a POSITIVE weight in every set and stage the cc CUTOFFS instead
# (WRCC/WDCC = -999 early, finite late).  The catalogue columns are left exactly
# as the catalogue-only baseline hypodd/year_v5_3d/hypoDD.inp has them
# (WRCT 6/6/4, WDCT -999 throughout), so the ONLY difference between the two
# runs is the presence of the cross-correlation data.
SCHEDULE = """  5     1.0   0.5   -999   -999   1.0    0.5    6    -999  400
  5     1.0   0.5   -999   -999   1.0    0.5    6    -999  400
  5     1.0   0.5    5      2     1.0    0.5    4    -999  400"""
# NB: no re.DOTALL here.  With (?s) the `.*` inside the data-line pattern eats
# newlines and the substitution swallows the whole forward-model + CID tail of
# the file; hypoDD then dies with "error: invalid cluster number 32544".
t, n = re.subn(r"(?m)^(\* NITER  WTCCP[^\n]*DAMP\n)(?:[ \t]*[-\d][^\n]*\n)+",
               lambda m: m.group(1) + SCHEDULE + "\n", t)
assert n == 1, f"expected exactly one re-weighting block, patched {n}"
assert t.rstrip().endswith("* ID"), "patch truncated the control file"
assert "IMOD" in t and "CID" in t, "patch removed the forward-model block"
open(p, "w").write(t)
print("patched OBSCC -> 0 and the re-weighting schedule in", p)
PY
sed -n '/OBSCC/,+2p;/NITER  WTCCP/,+3p' "$DST/hypoDD.inp"

python3 - "$DST" <<'PY' 2>&1 | tee -a "$DST/run24.log"
import importlib.util, json, subprocess, sys
from pathlib import Path
REPO = Path.cwd(); run = Path(sys.argv[1])
spec = importlib.util.spec_from_file_location("s24", REPO/"scripts"/"24_run_hypodd.py")
s24 = importlib.util.module_from_spec(spec); spec.loader.exec_module(s24)
binary = str(s24.DEFAULT_BIN_3D)
print("running", binary, "in", run)
proc = subprocess.run([binary, "hypoDD.inp"], cwd=run, capture_output=True)
log = proc.stdout.decode(errors="replace")
if proc.stderr:
    log += "\n---- stderr ----\n" + proc.stderr.decode(errors="replace")
(run/"hypoDD.log").write_text(log)
print(log[-2000:])
df = s24.parse_reloc(run/"hypoDD.reloc")
n_in = sum(1 for _ in (run/"event.sel").open())
print(f"  events: {n_in:,} in event.sel -> {len(df):,} relocated "
      f"({n_in-len(df):,} lost, {(n_in-len(df))/max(n_in,1)*100:.1f}%)")
shift = float(json.loads((run/"hypodd_datum.json").read_text())["datum_shift_km"])
df = s24.apply_depth_sanity_filter(df, shift)
out = REPO/"catalogs"/f"hypodd_{run.name}.csv"
df.to_csv(out, index=False)
print("Wrote", out, len(df), "relocated events")
PY

# ---- stage 4: evaluation
python3 scripts/55_synth_eval.py year_v5_3d year_v5_3d_xc 2>&1 | tee "$DST/eval55.log"
python3 scripts/50_hypodd_qc.py --label year_v5_3d_xc 2>&1 | tee "$DST/qc50.log"
echo "done."
